In [13]:
import numpy as np

import torch

In [39]:
# Building a Tensor

# Zeros
print(torch.zeros(1, 3))

# Ones
print(torch.ones(1, 3))

# Range
print(torch.arange(0,20,2))

# Random Uniform
print(torch.rand(1, 3))

# Random Normal
print(torch.randn(1, 3))

# From Numpy
print(torch.from_numpy(np.random.rand(1,3)))

tensor([[0., 0., 0.]])
tensor([[1., 1., 1.]])
tensor([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])
tensor([[0.2060, 0.6301, 0.9364]])
tensor([[ 0.6524, -1.9594,  1.2824]])
tensor([[0.9760, 0.6842, 0.7096]], dtype=torch.float64)


In [83]:
# Operations with One Tensor

x = torch.randn(3,1)
print(x)

# Size
print(x.size())
print(x.shape)

# Type
print(x.type())

# View
print(x.view(3,1))

# Sum
print(torch.sum(x, dim=0))
print(torch.sum(x, dim=1))

# Fill
print(x.fill_(5))

# Transposing
# if the vector has only one dimension declared, it cannot be transposed
print(torch.transpose(x,0,1))

tensor([[-0.3333],
        [ 0.9970],
        [-0.3619]])
torch.Size([3, 1])
torch.Size([3, 1])
torch.FloatTensor
tensor([[-0.3333],
        [ 0.9970],
        [-0.3619]])
tensor([0.3017])
tensor([-0.3333,  0.9970, -0.3619])
tensor([[5.],
        [5.],
        [5.]])
tensor([[5., 5., 5.]])


In [73]:
# Operations with Two Tensors

x = torch.randn(3)
y = torch.randn(3)

print(x)
print(y)

print(x + y)
print(x - y)
print(x * y)
print(x / y)
print(x // y)
print(x % y)

tensor([-1.4989, -0.8321, -0.1773])
tensor([-0.4894, -0.7904,  0.0652])
tensor([-1.9883, -1.6225, -0.1121])
tensor([-1.0095, -0.0417, -0.2425])
tensor([ 0.7336,  0.6577, -0.0116])
tensor([ 3.0627,  1.0527, -2.7179])
tensor([ 3.,  1., -2.])
tensor([-0.0307, -0.0417,  0.0184])


In [96]:
# Indexing

x = torch.randn(10, 10)

# Continuous
print(x[5:,5:])

# Non-Continuous
sup_row = torch.arange(0,10,2)
sup_col = torch.arange(0,10,2)

#print(x[sup_row,sup_col])

print(torch.index_select(x, dim=1, index=sup))

tensor([[-1.4362,  0.0848,  0.1389, -0.0744, -1.7255],
        [-0.8913, -0.2077,  0.3700, -0.7531,  0.4664],
        [-0.0087,  0.7635, -0.1706, -1.0538, -1.3968],
        [ 1.3717,  0.1266,  0.8154, -0.6864, -1.3161],
        [-3.2332,  0.1130,  0.4104,  1.3040,  1.3087]])
tensor([[ 1.0163,  0.4716,  1.4737,  1.3516, -0.1554],
        [-0.5986, -0.5914,  0.3905, -0.0702,  0.6813],
        [ 0.9357, -2.3559, -1.4715,  1.3561, -1.4806],
        [-0.1969, -1.4514,  0.9842, -0.4019,  0.6894],
        [ 0.5601, -1.5214,  0.6925, -0.3088, -0.2584],
        [ 1.5533,  0.1385,  1.6722,  0.0848, -0.0744],
        [ 1.1507, -0.1576, -0.1645, -0.2077, -0.7531],
        [ 2.1669,  0.4073, -1.0519,  0.7635, -1.0538],
        [ 0.0026,  0.7550,  0.4742,  0.1266, -0.6864],
        [ 0.8898, -0.6995,  1.0804,  0.1130,  1.3040]])
